name       : networkmanager-pptp
version    : 1.2.6
release    : 10
source     :
    - https://download.gnome.org/sources/NetworkManager-pptp/1.2/NetworkManager-pptp-1.2.6.tar.xz : c3292ec8769c391f9179e5aa74d01c2bbb697c91598e9485ac2e97fafc4745b4
license    : GPL-2.0
component  : network.base
summary    : PPTP support for NetworkManager
description: |
    PPTP support for NetworkManager
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(libsecret-1)
    - pkgconfig(libnm-gtk)
    - ppp-devel
rundeps    :
    - pptp
    - ppp
setup      : |
    %configure --disable-static \
               --with-pppd-plugin-dir=/usr/lib/pppd/2.4.7
build      : |
    %make
install    : |
    %make_install
