name       : networkmanager-pptp
version    : 1.2.12
release    : 20
source     :
    - https://download.gnome.org/sources/NetworkManager-pptp/1.2/NetworkManager-pptp-1.2.12.tar.xz : e5fa59fe46117f0ee86e9ca62c6943bc063884b04dd2396ccec38a2d1f414982
license    : GPL-2.0-or-later
component  : network.base
summary    : PPTP support for NetworkManager
description: |
    PPTP support for NetworkManager
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(gtk+-3.0)
    - pkgconfig(libnma)
    - pkgconfig(libsecret-1)
    - pkgconfig(mm-glib)
    - ppp-devel
rundeps    :
    - pptp
    - ppp
setup      : |
    %reconfigure --disable-static --with-pppd-plugin-dir=/usr/lib/pppd/2.4.8
build      : |
    %make
install    : |
    %make_install
