name       : networkmanager-pptp
version    : 1.0.8
release    : 1
source     :
    - https://download.gnome.org/sources/NetworkManager-pptp/1.0/NetworkManager-pptp-1.0.8.tar.xz : 6ff031baf170d890f779cfd15533ff0429999f1513aa3903a60c9d21ae09244c
license    : GPL-2.0
component  : network.base
summary    : PPTP support for NetworkManager
description: |
    PPTP support for NetworkManager
builddeps  :
    - pkgconfig(libsecret-1)
    - pkgconfig(libnm-gtk)
    - ppp-devel
rundeps    :
    - pptp
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
