name       : networkmanager-pptp
version    : 1.2.4
release    : 6
source     :
    - https://ftp.gnome.org/pub/gnome/sources/NetworkManager-pptp/1.2/NetworkManager-pptp-1.2.4.tar.xz : bd97ce768c34cce6d5b5d43681149a8300bec754397a3f46a0d8d0aea7030c5e
license    : GPL-2.0
component  : network.base
summary    : PPTP support for NetworkManager
description: |
    PPTP support for NetworkManager
builddeps  :
    - pkgconfig(dbus-glib-1)
    - pkgconfig(libsecret-1)
    - pkgconfig(libnm-gtk)
    - ppp-devel
rundeps    :
    - pptp
    - ppp
setup      : |
    %configure --disable-static \
               --with-pppd-plugin-dir=/usr/lib/pppd/2.4.7
build      : |
    %make
install    : |
    %make_install
